export const demo = {
  missions: [
    {
      id: "S01",
      role: "Founder / Strategist",
      title: "Make the decision inspectable.",
      division: "THE COLLECTIVE",
      level: "Intermediate",
      duration: "2–3 hours",
      stack: "Perplexity → Claude → Notion",
      mission:
        "Build a one-page decision memo for a fictional Columbus service business choosing its first AI workflow.",
      inputs:
        "A business brief, customer pain points, budget, and three official product sources.",
      deliver: "Decision memo, claim ledger, and a 14-day experiment.",
      gate: "Every factual claim has a source. The experiment fits the budget and has an accountable owner.",
      page: 52,
      xp: 300,
    },
    {
      id: "S02",
      role: "Researcher / Editor",
      title: "Publish a story that survives checking.",
      division: "COLLECTIVE TIMES",
      level: "Beginner",
      duration: "90 minutes",
      stack: "Perplexity → Gemini Notebook → Claude",
      mission: "Create a source-grounded briefing with a fact-check sheet.",
      inputs: "An official announcement and developer documentation.",
      deliver: "Briefing and five-item fact-check sheet.",
      gate: "Every consequential claim is traceable.",
      page: 53,
      xp: 200,
    },
    {
      id: "S05",
      role: "Game Developer / Technical Artist",
      title: "Make the reference playable.",
      division: "NEXUS LABS",
      level: "Advanced",
      duration: "1–2 days",
      stack: "Reference pack → Tripo → Blender → Three.js → Codex",
      mission:
        "Build a distinctive kart and driver as a playable, animated vertical slice.",
      inputs: "Matched reference views and a target-device budget.",
      deliver: "Source asset, GLB, playable scene, and device record.",
      gate: "Identity matches, controls work, and the actual phone meets the frame budget.",
      page: 56,
      xp: 600,
    },
  ],
  tools: [],
  models: [],
  combos: [],
  pages: [],
};
export const districts = [
  {
    name: "The Strategy Hall",
    short: "Strategy",
    desc: "Decisions. Research. Direction.",
    color: "#d6b274",
    ids: ["S01", "S02", "S08"],
    icon: "compass",
  },
  {
    name: "The Maker’s Foundry",
    short: "Build",
    desc: "Code. Systems. Playable worlds.",
    color: "#88b9a1",
    ids: ["S04", "S05", "S11"],
    icon: "box",
  },
  {
    name: "The Creative Atelier",
    short: "Create",
    desc: "Design. Film. Distinctive craft.",
    color: "#ac9bd1",
    ids: ["S03", "S06"],
    icon: "sparkles",
  },
  {
    name: "The Operations Wing",
    short: "Operate",
    desc: "People. Workflows. Reliable delivery.",
    color: "#85adca",
    ids: ["S07", "S10", "S12"],
    icon: "workflow",
  },
  {
    name: "The Mentor’s Chamber",
    short: "Teach",
    desc: "Practice. Feedback. Shared standards.",
    color: "#d39178",
    ids: ["S09"],
    icon: "users",
  },
];
